In [1]:
import tensorflow as tf # import tensorflow

Init Plugin
Init Graph Optimizer
Init Kernel


In [2]:
mnist = tf.keras.datasets.mnist # load mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data() # load data from mnist

In [4]:
model = tf.keras.models.Sequential([ # create a sequentially layered model
    tf.keras.layers.Flatten(input_shape=(28, 28)), # 'flatten' multidimensional input to 1D output
    tf.keras.layers.Dense(128, activation='relu'), # subsequent neurons have connections to all other prior neurons
    tf.keras.layers.Dropout(0.2), # prevent overfitting
    tf.keras.layers.Dense(10) # output with 10 dimensions
])

Metal device set to: Apple M1


2022-07-06 15:23:06.527883: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-07-06 15:23:06.528185: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [10]:
predictions = model(x_train[:1]).numpy() # predictions from model of the first cell of the training x data
predictions

array([[ 109.440674,  -56.062954,    4.429161,   25.45996 , -177.85928 ,
         -81.903595,  -71.37429 ,  220.72215 ,   78.90222 ,  156.23642 ]],
      dtype=float32)

In [13]:
probabilities = tf.nn.softmax(predictions).numpy() # activation functions to output probabilities
probabilities

array([[0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
        0.000000e+00, 9.867371e-29]], dtype=float32)

In [15]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True) # diff between expected and produced quantified
initial_loss = loss_fn(y_train[:1], predictions).numpy() # expected first cell, produced; quantified
initial_loss

302.62573

In [16]:
model.compile(optimizer='adam', # compile model using learning rate optimizer
              loss = loss_fn, # measures how good the algorithms models the data set
              metrics = ['accuracy']) # check accuracy

In [18]:
model.fit(x_train, y_train, epochs=5) # train model

2022-07-06 15:37:27.431234: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2022-07-06 15:37:27.431430: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-07-06 15:37:27.576685: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


Epoch 1/5
1875/1875 [==============================] - 7s 4ms/step - loss: 2.6774 - accuracy: 0.7538
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.6152 - accuracy: 0.8380
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.4885 - accuracy: 0.8751
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.4254 - accuracy: 0.8907
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.3808 - accuracy: 0.9025


In [19]:
model.evaluate(x_test, y_test, verbose=2) # evaluate model

2022-07-06 15:41:26.469595: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


313/313 - 1s - loss: 0.2982 - accuracy: 0.9329


[0.29815033078193665, 0.932900071144104]

In [22]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax() # apply activation function
])
probability_model(x_test[:5]) # probability of the model up to 5th cell

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.00000000e+00, 4.59512040e-13, 3.33368194e-11, 6.34492947e-09,
        1.98784847e-12, 1.44386229e-17, 0.00000000e+00, 1.00000000e+00,
        1.09059746e-35, 1.98759923e-15],
       [3.34717258e-12, 4.95174675e-08, 9.99999642e-01, 2.16364580e-08,
        0.00000000e+00, 2.82257976e-26, 4.48725037e-25, 2.52221270e-07,
        4.28821215e-12, 2.62233798e-33],
       [0.00000000e+00, 9.99999523e-01, 1.96364973e-12, 1.31123161e-12,
        2.13955520e-11, 5.29860200e-23, 1.38060667e-24, 4.56344139e-07,
        4.40080555e-10, 5.65926718e-26],
       [1.00000000e+00, 3.48105056e-33, 4.76972739e-10, 1.11032989e-13,
        5.92133561e-14, 1.41407229e-14, 2.81495442e-14, 4.35672443e-10,
        8.13384934e-16, 4.37861553e-12],
       [3.22080931e-13, 1.19758911e-10, 1.33467950e-06, 3.07804088e-10,
        9.99992490e-01, 1.26922306e-09, 3.09986831e-07, 7.98219332e-07,
        6.72202162e-14, 5.08939138e-06]], dtype=float32)>